### PR TITLE
Replace assertRegExp with assertMatchesRegularExpression in unit test

### LINKED ISSUE #507: phpunit CI fails on PHP 7.4
Example CI run in PR #506 

https://travis-ci.org/github/sabre-io/vobject/jobs/700625965
```
There was 1 warning:

1) Sabre\VObject\CliTest::testRepair

assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.

WARNINGS!

Tests: 1709, Assertions: 2628, Warnings: 1.
```

### PR DESCRIPTION
**Pull request by phil-davis**
Fixes #507 

To avoid:
```
There was 1 warning:

1) Sabre\VObject\CliTest::testRepair

assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.
```

e.g. https://travis-ci.org/github/sabre-io/dav/jobs/700622019 where the unit test fails in `sabre-io/dav` https://github.com/sabre-io/dav/pull/1275

### CODE REVIEW

**Comment by phil-davis** [comment]
It's a PITA - the new `assertMatchesRegularExpression` does not seem to exist in `phpunit` 7 or 8. It is new in `phpunit` 9, and already there is a warning about it being removed in `phpunit` 10.

Looks like it needs some "if method exists" code.

**Comment by phil-davis** [comment]
All Travis CI phpunit results now have no warnings/errors.

**Comment by phil-davis** [comment]
These tests seem to get reused in `sabre-io/dav`. I guess this will need a `vobject` release so that the unit test change gets seen in the downstream repo?

File: tests/VObject/CliTest.php [hunk 1]
```diff
@@ -483,7 +483,13 @@ public function testRepair()
         );
 
         rewind($this->cli->stdout);
-        $this->assertRegExp("/^BEGIN:VCARD\r\nVERSION:2.1\r\nUID:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\r\nEND:VCARD\r\n$/", stream_get_contents($this->cli->stdout));
+        $regularExpression = "/^BEGIN:VCARD\r\nVERSION:2.1\r\nUID:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\r\nEND:VCARD\r\n$/";
+        $data = stream_get_contents($this->cli->stdout);
+        if (method_exists($this, 'assertMatchesRegularExpression')) {
```
Comment (staabm) [inline tests/VObject/CliTest.php:488]: maybe we coud do a regular preg_match() instead and assert the return value?

Comment (phil-davis) [reply tests/VObject/CliTest.php:488]: The asserts that come with `phpunit` are nice. It is just this transition thing that is a bit annoying - the warnings start coming too quickly making it difficult to have a unit test code base that works with many phpunit major versions.

Comment (phil-davis) [reply tests/VObject/CliTest.php:490]: I added a "ToDo" so that when someone comes across this in 2 years time, they will easily be confident to clean it up.

Comment (phil-davis) [reply tests/VObject/CliTest.php:490]: @staabm are you OK with the ToDo and using the the "built-in" assert methods?
Or do you want me to use a "manual" `preg_match` plus assert result?
