### PR TITLE
ITip\Broker: handle timezones in replies to exception events

### LINKED ISSUE #358: Broker::processMessageReply
Currently, `Broker::processMessageReply` ignore exceptions that have a recurrent id in a different time-zone than the DTSTART of the master event.
This cause issue in Sabre when a attendee update his partstat on an instance using a client that use UTC for recurrent id.

### PR DESCRIPTION
**Pull request by gharlan**
fixes #358, closes #360

While rebasing #360, I noticed that it only fixes replies to new exception events. I use a different approach now, which also fixes replies to existing exception events.

### CODE REVIEW

File: tests/VObject/ITip/BrokerProcessReplyTest.php [hunk 1]
```diff
@@ -253,6 +253,73 @@ public function testReplyPartyCrasher(): void
         $this->process($itip, $old, $expected);
     }
 
+    public function testReplyExistingExceptionRecurrenceIdInUTC(): void
```
Comment (phil-davis) [inline tests/VObject/ITip/BrokerProcessReplyTest.php:256]: Is this the same test case as `testReplyNewExceptionRecurrenceIdInUTC` further down?

File: tests/VObject/ITip/BrokerProcessReplyTest.php [hunk 2]
```diff
@@ -373,6 +440,126 @@ public function testReplyNewExceptionTz(): void
         $this->process($itip, $old, $expected);
     }
 
+    public function testReplyNewExceptionRecurrenceIdInDifferentTz(): void
+    {
+        // This is a reply to 1 instance of a recurring event. This should
+        // automatically create an exception.
```
Comment (phil-davis) [inline tests/VObject/ITip/BrokerProcessReplyTest.php:446]:
```suggestion
        // This is a reply to 1 instance of a recurring event.
```

I don't understand why this comment had "This should automatically create an exception."

File: tests/VObject/ITip/BrokerProcessReplyTest.php [hunk 3]
```diff
@@ -373,6 +440,126 @@ public function testReplyNewExceptionTz(): void
...
+END:VCALENDAR
+ICS;
+
+        $this->process($itip, $old, $expected);
+    }
+
+    public function testReplyNewExceptionRecurrenceIdInUTC(): void
+    {
+        // This is a reply to 1 instance of a recurring event. This should
+        // automatically create an exception.
```
Comment (phil-davis) [inline tests/VObject/ITip/BrokerProcessReplyTest.php:506]:
```suggestion
        // This is a reply to 1 instance of a recurring event.
```

I don't understand why this comment had "This should automatically create an exception."

File: tests/VObject/ITip/BrokerProcessReplyTest.php (hunk 1 above)
Comment (gharlan) [reply tests/VObject/ITip/BrokerProcessReplyTest.php:256]: No, here the exception event already exists in `$old`. So it is a reply to an existing exception event, which wasn't covered/fixed by the original pull request.

File: lib/ITip/Broker.php [hunk 4]
```diff
@@ -333,7 +333,7 @@ protected function processMessageReply(Message $itipMessage, ?VCalendar $existin
 
         // Finding all the instances the attendee replied to.
         foreach ($itipMessage->message->VEVENT as $vevent) {
-            $recurId = isset($vevent->{'RECURRENCE-ID'}) ? $vevent->{'RECURRENCE-ID'}->getValue() : 'master';
+            $recurId = isset($vevent->{'RECURRENCE-ID'}) ? $vevent->{'RECURRENCE-ID'}->getDateTime()->getTimestamp() : 'master';
```
Comment (phil-davis) [inline lib/ITip/Broker.php:336]: Note for myself ( and maybe helps others):
https://www.php.net/manual/en/datetime.gettimestamp.php returns the Unix timestamp (seconds since "Unix zero time").

So that is a unique number that corresponds to the day-and-time of the particular event. If that timestamp of a recurrence matches the timestamp of a reply, then we know that it is a reply to that occurrence of the event - seems good to me.

File: tests/VObject/ITip/BrokerProcessReplyTest.php (hunk 2 above)
Comment (gharlan) [reply tests/VObject/ITip/BrokerProcessReplyTest.php:446]: It is a copy/paste from all existing `testReplyNewException...` test cases.
The original event didn't had the exception, but the attendee replies to one recurrence only. So the reply should create the exception event.

File: lib/ITip/Broker.php (hunk 4 above)
Comment (gharlan) [reply lib/ITip/Broker.php:336]: Yes, the unix timestamp avoids the timezone problem

File: tests/VObject/ITip/BrokerProcessReplyTest.php (hunk 2 above)
Comment (phil-davis) [reply tests/VObject/ITip/BrokerProcessReplyTest.php:446]: My brain was thinking "exception" as in "throw an exception"!
But in this context, "exception event" means a recurrence of a recurring event that has "something different" about it. In this case, it has an attendee who is attending that particular recurrence of the event.

All good.

File: tests/VObject/ITip/BrokerProcessReplyTest.php (hunk 3 above)
Comment (phil-davis) [reply tests/VObject/ITip/BrokerProcessReplyTest.php:506]: See comments for the same comment in the previous test case.

**Review by staabm — APPROVED** [review]
I don't see obvious problems

File: lib/ITip/Broker.php (hunk 4 above)
Comment (phil-davis) [reply lib/ITip/Broker.php:339]: I pushed a commit that adds comments about the use of getTimestamp()

**Review by phil-davis — APPROVED** [review]
